# Generated by Django 5.0.3 on 2024-04-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="patronymic",
            field=models.CharField(
                blank=True,
                help_text="При наличии",
                max_length=256,
                null=True,
                verbose_name="Отчество",
            ),
        ),
    ]
