# Generated by Django 5.0.3 on 2024-04-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_patronymic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
    ]
