# Generated by Django 5.0.3 on 2024-04-03 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата создания пользователя"
            ),
        ),
    ]
