# Generated by Django 5.0.3 on 2024-04-01 13:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collect_name",
                    models.CharField(max_length=256, verbose_name="Название"),
                ),
                ("reason", models.CharField(max_length=256, verbose_name="Повод")),
                ("description", models.TextField(verbose_name="Описание сбора")),
                (
                    "collect_goal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цель сбора",
                    ),
                ),
                (
                    "collected_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Сколько уже собрали",
                    ),
                ),
                (
                    "person_count",
                    models.IntegerField(
                        default=1, verbose_name="Сколько человек участвует в сборе"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Обложка"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата конца сбора средств"
                    ),
                ),
                (
                    "collect_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                        verbose_name="Владелец сбора",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonatersList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donate_sum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма пожертвования",
                    ),
                ),
                (
                    "donate_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Дата пожертвования"
                    ),
                ),
                (
                    "donate_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundraising.collect",
                        verbose_name="Куда донатил",
                    ),
                ),
                (
                    "doneter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                        verbose_name="Донатер",
                    ),
                ),
            ],
        ),
    ]
