# Generated by Django 5.0.3 on 2024-04-01 13:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Статус сбора"),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма пожертвования",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Дата пожертвования"
                    ),
                ),
                (
                    "pay_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundraising.collect",
                        verbose_name="Ключ на `collect`",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userprofile",
                        verbose_name="Ключ на `user_profile`",
                    ),
                ),
            ],
        ),
    ]
