# Generated by Django 5.0.3 on 2024-04-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0002_collect_status_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DonatersList",
        ),
    ]
