# Generated by Django 5.0.3 on 2024-04-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0007_alter_collect_options_alter_payment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collect",
            options={"verbose_name": "Сбор", "verbose_name_plural": "Сборы"},
        ),
    ]
