# Generated by Django 5.0.3 on 2024-04-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0008_alter_collect_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="person_count",
            field=models.IntegerField(
                default=0, verbose_name="Сколько человек участвует в сборе"
            ),
        ),
    ]
