# Generated by Django 5.0.3 on 2024-04-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraising", "0009_alter_collect_person_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="contributors",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Список идентификаторов донатеров",
            ),
        ),
    ]
